import { useRef } from 'react';
import { toPng } from 'html-to-image';
import { Heading, getProfileSummary } from '@/lib/headings';

interface VoiceDNATabProps {
  activeHeading: Heading | null;
}

export function VoiceDNATab({ activeHeading }: VoiceDNATabProps) {
  const cardRef = useRef<HTMLDivElement>(null);

  if (!activeHeading) {
    return (
      <div className="flex-1 flex flex-col items-center justify-center gap-4 py-20 animate-fade-in">
        <div className="w-20 h-20 rounded-2xl bg-warm-bg flex items-center justify-center">
          <span className="text-3xl">&#127912;</span>
        </div>
        <p className="text-ink-text text-lg font-medium">Create a voice profile to see your DNA</p>
        <p className="text-slate-text text-sm">Your unique writing fingerprint, visualized</p>
      </div>
    );
  }

  const profile = activeHeading.profile;
  const summary = getProfileSummary(profile);
  const sampleCount = activeHeading.samples.length;
  const confidence = sampleCount >= 5 ? 'High' : sampleCount >= 3 ? 'Moderate' : 'Low';
  const confidenceColor = sampleCount >= 5 ? 'text-signal-cyan' : sampleCount >= 3 ? 'text-brass' : 'text-alert-coral';

  const traits = [
    { label: 'Sentence rhythm', value: `${Math.round(profile.sentenceLength.mean)} words avg`, sub: profile.sentenceLength.stdDev > 8 ? 'Wide variation' : 'Consistent' },
    { label: 'Punctuation style', value: profile.punctuation.emDashes > 5 ? 'Em-dash heavy' : profile.punctuation.exclamationPoints > 10 ? 'Exclamation-forward' : 'Standard', sub: `${profile.punctuation.emDashes.toFixed(1)} dashes / 100w` },
    { label: 'Vocabulary range', value: `${Math.round(profile.lexicalDiversity.mean * 100)}% diverse`, sub: `${Math.round(profile.contractionRate * 100)}% contractions` },
    { label: 'Filler presence', value: profile.fillerWords.frequency > 5 ? 'Frequent' : profile.fillerWords.frequency > 2 ? 'Moderate' : 'Minimal', sub: `${profile.fillerWords.frequency.toFixed(1)} / 100 words` },
  ];

  const handleExport = async () => {
    if (!cardRef.current) return;
    try {
      const dataUrl = await toPng(cardRef.current, { width: 640, height: 420, pixelRatio: 2 });
      const link = document.createElement('a');
      link.href = dataUrl;
      link.download = `drift-dna-${activeHeading.name.toLowerCase().replace(/\s+/g, '-')}.png`;
      link.click();
    } catch (err) { console.error('Export failed:', err); }
  };

  const handleCopy = async () => {
    const text = [
      `Voice DNA: ${activeHeading.name}`,
      activeHeading.description, '',
      ...summary.map(s => `- ${s}`), '',
      `Confidence: ${confidence} (${sampleCount} samples)`, '',
      'Generated by Drift — your voice, unflattened',
    ].join('\n');
    await navigator.clipboard.writeText(text);
  };

  return (
    <div className="max-w-3xl mx-auto py-8 px-6 space-y-8 tab-content-enter">
      <div className="text-center animate-fade-in">
        <h2 className="text-xl font-bold text-ink-text">Voice DNA</h2>
        <p className="text-sm text-slate-text mt-1">Your unique writing fingerprint, visualized</p>
      </div>

      {/* DNA Card — dark card for visual contrast and shareability */}
      <div ref={cardRef}
        className="w-full aspect-[3/2] rounded-2xl p-8 flex flex-col justify-between relative overflow-hidden animate-fade-in shadow-lg"
        style={{ background: 'linear-gradient(135deg, #1a1f2e 0%, #141820 50%, #1a1f2e 100%)' }}>
        <div className="absolute top-4 right-4 opacity-10">
          <svg width="100" height="100" viewBox="0 0 100 100">
            <circle cx="50" cy="50" r="46" fill="none" stroke="#B8863A" strokeWidth="1" />
            <circle cx="50" cy="50" r="30" fill="none" stroke="#2D9F83" strokeWidth="0.5" />
            <polygon points="50,10 47,50 50,48 53,50" fill="#B8863A" opacity="0.5" />
            <polygon points="50,90 47,50 50,52 53,50" fill="#2D9F83" opacity="0.5" />
            <circle cx="50" cy="50" r="3" fill="#F9F7F4" />
          </svg>
        </div>

        <div>
          <p className="text-xs font-medium text-[#4FD8C4]/60 tracking-widest uppercase mb-2">Voice DNA</p>
          <h3 className="text-3xl font-bold text-[#B8863A] mb-1">{activeHeading.name}</h3>
          <p className="text-sm text-[#C9D3DC]/50">{activeHeading.description}</p>
        </div>

        <div className="grid grid-cols-2 gap-x-8 gap-y-3">
          {traits.map((trait, i) => (
            <div key={i}>
              <p className="text-xs text-[#C9D3DC]/40">{trait.label}</p>
              <p className="text-sm text-[#C9D3DC]">{trait.value}</p>
              <p className="text-xs text-[#C9D3DC]/30">{trait.sub}</p>
            </div>
          ))}
        </div>

        {profile.topPhrases && profile.topPhrases.length > 0 && (
          <div>
            <p className="text-xs text-[#C9D3DC]/30 mb-1">Signature phrases</p>
            <p className="text-sm text-[#B8863A]/80">
              {profile.topPhrases.slice(0, 4).map(p => `"${p}"`).join('  ·  ')}
            </p>
          </div>
        )}

        <div className="flex items-center justify-between pt-3 border-t border-[#C9D3DC]/10">
          <p className="text-xs text-[#C9D3DC]/30">drift — your voice, unflattened</p>
          <div className="flex items-center gap-3">
            <span className={`text-xs ${confidence === 'High' ? 'text-[#4FD8C4]' : confidence === 'Moderate' ? 'text-[#B8863A]' : 'text-[#C4574A]'}`}>
              {confidence} confidence
            </span>
            <span className="text-xs text-[#C9D3DC]/20">{new Date().toLocaleDateString()}</span>
          </div>
        </div>
      </div>

      <div className="flex gap-3 justify-center animate-fade-in" style={{ animationDelay: '0.1s' }}>
        <button onClick={handleExport} className="btn-primary">Export as PNG</button>
        <button onClick={handleCopy} className="btn-secondary">Copy as text</button>
      </div>

      <div className="space-y-4 animate-fade-in" style={{ animationDelay: '0.15s' }}>
        <h3 className="text-sm font-semibold text-ink-text text-center">Voice traits</h3>
        <div className="space-y-2">
          {summary.map((bullet, i) => (
            <div key={i} className="card-panel flex items-start gap-3">
              <span className="text-brass mt-0.5 text-xs">&#9679;</span>
              <p className="text-sm text-slate-text">{bullet}</p>
            </div>
          ))}
        </div>
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
          {[
            { label: 'Sentences', value: String(profile.sentenceCount || '--') },
            { label: 'Paragraphs', value: String(profile.paragraphCount || '--') },
            { label: 'AI Cliches', value: String(profile.aiClicheCount || 0) },
            { label: 'Samples', value: String(sampleCount) },
          ].map((stat, i) => (
            <div key={i} className="card-panel text-center">
              <p className="text-lg font-bold text-brass">{stat.value}</p>
              <p className="text-xs text-slate-text/60">{stat.label}</p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
