import { useRef } from 'react';
import { toPng } from 'html-to-image';
import { Heading, getProfileSummary } from '@/lib/headings';

interface VoiceDNATabProps {
  activeHeading: Heading | null;
}

export function VoiceDNATab({ activeHeading }: VoiceDNATabProps) {
  const cardRef = useRef<HTMLDivElement>(null);

  if (!activeHeading) {
    return (
      <div className="flex-1 flex flex-col items-center justify-center gap-4 py-20">
        <svg width="80" height="80" viewBox="0 0 80 80" className="text-slate-text/15">
          <circle cx="40" cy="40" r="36" fill="none" stroke="currentColor" strokeWidth="1.5" />
          <circle cx="40" cy="40" r="20" fill="none" stroke="currentColor" strokeWidth="0.8" opacity="0.5" />
          <circle cx="40" cy="40" r="4" fill="currentColor" />
        </svg>
        <p className="text-slate-text/50 font-spectral text-lg">Create a voice profile to see your DNA</p>
      </div>
    );
  }

  const profile = activeHeading.profile;
  const summary = getProfileSummary(profile);
  const sampleCount = activeHeading.samples.length;

  const confidence = sampleCount >= 5 ? 'High' : sampleCount >= 3 ? 'Moderate' : 'Low';
  const confidenceColor = sampleCount >= 5 ? 'text-signal-cyan' : sampleCount >= 3 ? 'text-brass' : 'text-alert-coral';

  const traits = [
    { label: 'Sentence rhythm', value: `${Math.round(profile.sentenceLength.mean)} words avg`, sub: profile.sentenceLength.stdDev > 8 ? 'Wide variation' : 'Consistent' },
    { label: 'Punctuation style', value: profile.punctuation.emDashes > 5 ? 'Em-dash heavy' : profile.punctuation.exclamationPoints > 10 ? 'Exclamation-forward' : 'Standard', sub: `${profile.punctuation.emDashes.toFixed(1)} dashes / 100w` },
    { label: 'Vocabulary range', value: `${Math.round(profile.lexicalDiversity.mean * 100)}% diverse`, sub: `${Math.round(profile.contractionRate * 100)}% contractions` },
    { label: 'Filler presence', value: profile.fillerWords.frequency > 5 ? 'Frequent' : profile.fillerWords.frequency > 2 ? 'Moderate' : 'Minimal', sub: `${profile.fillerWords.frequency.toFixed(1)} / 100 words` },
  ];

  const handleExport = async () => {
    if (!cardRef.current) return;
    try {
      const dataUrl = await toPng(cardRef.current, { width: 640, height: 420, pixelRatio: 2 });
      const link = document.createElement('a');
      link.href = dataUrl;
      link.download = `drift-dna-${activeHeading.name.toLowerCase().replace(/\s+/g, '-')}.png`;
      link.click();
    } catch (err) {
      console.error('Export failed:', err);
    }
  };

  const handleCopy = async () => {
    const text = [
      `Voice DNA: ${activeHeading.name}`,
      `${activeHeading.description}`,
      '',
      ...summary.map(s => `- ${s}`),
      '',
      `Confidence: ${confidence} (${sampleCount} samples)`,
      '',
      'Generated by Drift — your voice, unflattened',
    ].join('\n');
    await navigator.clipboard.writeText(text);
  };

  return (
    <div className="max-w-3xl mx-auto py-8 px-6 space-y-8">
      <div className="text-center">
        <h2 className="text-xl font-fraunces font-bold text-slate-text">Voice DNA</h2>
        <p className="text-sm text-slate-text/40 font-mono mt-1">Your unique writing fingerprint, visualized</p>
      </div>

      {/* DNA Card */}
      <div
        ref={cardRef}
        className="w-full aspect-[3/2] rounded-lg p-8 flex flex-col justify-between relative overflow-hidden"
        style={{
          background: 'linear-gradient(135deg, #101826 0%, #0a0f17 50%, #101826 100%)',
          border: '1px solid rgba(201, 211, 220, 0.12)',
        }}
      >
        {/* Decorative circles */}
        <div className="absolute top-4 right-4 opacity-10">
          <svg width="120" height="120" viewBox="0 0 120 120">
            <circle cx="60" cy="60" r="58" fill="none" stroke="#C98A3E" strokeWidth="0.5" />
            <circle cx="60" cy="60" r="40" fill="none" stroke="#4FD8C4" strokeWidth="0.5" />
            <circle cx="60" cy="60" r="22" fill="none" stroke="#C98A3E" strokeWidth="0.5" />
            <circle cx="60" cy="60" r="4" fill="#C98A3E" />
            <line x1="60" y1="60" x2="60" y2="10" stroke="#C98A3E" strokeWidth="1" strokeLinecap="round" />
          </svg>
        </div>

        {/* Header */}
        <div>
          <p className="text-xs font-mono text-signal-cyan/60 uppercase tracking-widest mb-2">Voice DNA</p>
          <h3 className="text-3xl font-fraunces font-bold text-brass mb-1">{activeHeading.name}</h3>
          <p className="text-sm text-slate-text/50 font-mono">{activeHeading.description}</p>
        </div>

        {/* Traits grid */}
        <div className="grid grid-cols-2 gap-x-8 gap-y-3">
          {traits.map((trait, i) => (
            <div key={i}>
              <p className="text-xs font-mono text-slate-text/40 uppercase">{trait.label}</p>
              <p className="text-sm font-spectral text-slate-text">{trait.value}</p>
              <p className="text-xs font-mono text-slate-text/30">{trait.sub}</p>
            </div>
          ))}
        </div>

        {/* Signature phrases */}
        {profile.topPhrases && profile.topPhrases.length > 0 && (
          <div>
            <p className="text-xs font-mono text-slate-text/30 mb-1">Signature phrases</p>
            <p className="text-sm font-spectral text-brass/80">
              {profile.topPhrases.slice(0, 4).map(p => `"${p}"`).join('  ·  ')}
            </p>
          </div>
        )}

        {/* Footer */}
        <div className="flex items-center justify-between pt-3 border-t border-slate-text/10">
          <div className="flex items-center gap-2">
            <span className="text-xs font-mono text-slate-text/30">drift</span>
            <span className="text-xs font-mono text-slate-text/15">·</span>
            <span className="text-xs font-mono text-slate-text/30">your voice, unflattened</span>
          </div>
          <div className="flex items-center gap-3">
            <span className={`text-xs font-mono ${confidenceColor}`}>{confidence} confidence</span>
            <span className="text-xs font-mono text-slate-text/20">{new Date().toLocaleDateString()}</span>
          </div>
        </div>
      </div>

      {/* Actions */}
      <div className="flex gap-3 justify-center">
        <button onClick={handleExport} className="btn-primary">Export as PNG</button>
        <button onClick={handleCopy} className="btn-secondary">Copy as Text</button>
      </div>

      {/* Detailed traits */}
      <div className="space-y-4">
        <h3 className="text-xs font-mono text-slate-text/40 uppercase tracking-wider text-center">Voice Traits</h3>
        <div className="space-y-2">
          {summary.map((bullet, i) => (
            <div key={i} className="card-panel flex items-start gap-3">
              <span className="text-brass mt-0.5">&#9670;</span>
              <p className="text-sm text-slate-text/80 font-spectral">{bullet}</p>
            </div>
          ))}
        </div>

        {/* Raw stats */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
          <StatBadge label="Sentences" value={String(profile.sentenceCount || '—')} />
          <StatBadge label="Paragraphs" value={String(profile.paragraphCount || '—')} />
          <StatBadge label="AI Cliches" value={String(profile.aiClicheCount || 0)} />
          <StatBadge label="Samples" value={String(sampleCount)} />
        </div>
      </div>
    </div>
  );
}

function StatBadge({ label, value }: { label: string; value: string }) {
  return (
    <div className="card-panel text-center">
      <p className="text-lg font-fraunces font-bold text-brass">{value}</p>
      <p className="text-xs font-mono text-slate-text/40 uppercase">{label}</p>
    </div>
  );
}
